### ISSUE TITLE
let string loading be easier

### ISSUE THREAD

**Issue by dannypsnl** [llir/llvm#209]
A common string using is like
```go
formatString = "array_def[%d]: %d\n"
fmtStr := mod.NewGlobalDef("x", constant.NewCharArrayFromString(formatString))
mainB := mod.NewFunc("main", types.I32).NewBlock("")
str := mainB.NewGetElementPtr(types.NewArray(uint64(len(formatString)), types.I8), fmtStr, CI32(0), CI32(0))
```
but that's quite annoying that we have to use GEP since in most cases we just want a pointer to the zero address of the string and the type of string is always the same.

Thus, I want to introduce API for this
```go
fmtStr := mod.NewGlobalDef("x", constant.NewCharArrayFromString("array_def[%d]: %d\n"))
mainB := mod.NewFunc("main", types.I32).NewBlock("")
str := mainB.LoadString(fmtStr)
// or
str := fmtStr.LoadTo(mainB)
```

I think the second one make more sense, since this pattern only useful for string literal

**Comment by mewmew** [comment]
Since LLVM IR is front end language agnostic, we cannot assume that the strings are NULL-terminated or [length-prefixed](https://en.wikipedia.org/wiki/String_(computer_science)#Length-prefixed). Thus, there may exist more than one reasonable implementation of a "get string" method.

For this reason, it belong well in an `irutil` library. Perhaps we could include two standard versions, one for NULL-terminated strings, and one for length-prefixed strings.

Cheers,
Robin

**Comment by dannypsnl** [comment]
sounds good

**Comment by dannypsnl** [comment]
I would create two API
1. c-string
2. p-string

**Comment by dannypsnl** [comment]
[here](https://github.com/llir/irutil/commit/c57eca4437aabdee0cc81c569d1d3fc23e951fd6), since we do have c-string now!

**Comment by dannypsnl** [comment]
ok...maybe the problem is should we add `Len` for `CharArray`?

**Comment by mewmew** [comment]
> ok...maybe the problem is should we add Len for CharArray?

`CharArray` is modelled from the character array of LLVM. It handles any kind of string, not just length-prefixed strings, so I think using `irutil` for this is the way to go.

To get the length of a `CharArray`, simply use `len`:

```go
c := constant.NewCharArrayFromString("foo")
n := len(c.X)
```
