### ISSUE TITLE
indirect br only takes constant addr

### ISSUE THREAD

**Issue by Chronostasys** [llir/llvm#217]
Hi,  
I'm trying to implement generator for my toy language following [this guide](https://mapping-high-level-constructs-to-llvm-ir.readthedocs.io/en/latest/advanced-constructs/generators.html), and I found `NewIndirectBr(addr constant.Constant, validTargets ...*Block) *TermIndirectBr`  only accepts constant address. However the first block address is calculated on the other function so I have to perform a store-and-load before using it, and it's not constant after load. I think `NewIndirectBr` should accept `value.Value` rather than `constant.Constant`.

**Comment by mewmew** [comment]
@Chronostasys, thanks for reporting this issue! You're right. It turns out you can pass an arbitrary `i8*` value to `indirectbr` (see example below).

We'll make sure to update the `llir/llvm` API to support `value.Value` as an operand to `indirectbr`.

```llvm
define i32 @main() {
entry:
	%address_data = alloca i8*
	store i8* inttoptr (i64 u0x41424344 to i8*), i8** %address_data
	%address = load i8*, i8** %address_data
	indirectbr i8* %address, [ label %block1, label %block2, label %block3, label %done ]

block1:
	ret i32 1

block2:
	ret i32 2

block3:
	ret i32 3

done:
	ret i32 0
}
```

```shell
$ clang -o foo foo.ll
$ gdb --args ./foo

(gdb) r
Starting program: ./foo
Program received signal SIGSEGV, Segmentation fault.
0x0000000041424344 in ?? ()
(gdb) 
```

**Note**: in the above example, I was surprised to see that LLVM does *not* validate the address to ensure it is present in the supplied list of basic blocks.

From https://llvm.org/docs/LangRef.html#i-indirectbr

> Address must be derived from a [blockaddress](https://llvm.org/docs/LangRef.html#blockaddress) constant.
>
> The rest of the arguments indicate the full set of possible destinations that the address may point to.
>
> All possible destination blocks must be listed in the label list, otherwise this instruction has undefined behavior.

So, turns out, in the above example, the undefined behaviour (is at least on my machine with LLVM 13.0) is to jump to the address *without* validation of the target address.

Cheers,
Robin
