### ISSUE TITLE
Feature: Specialized Metadata Nodes

### ISSUE THREAD

**Issue by zegl** [llir/llvm#26]
https://llvm.org/docs/LangRef.html#specialized-metadata-nodes

**Comment by mewmew** [comment]
Hej Gustav,

I would love to have specialized metadata nodes added to the grammar as that would provide access to DWARF metadata information. Last autumn we did some initial attempts to define the grammar, but the work is yet to be completed. Currently it is living in the [specialized-metadata-nodes](https://github.com/llir/grammar/tree/specialized-metadata-nodes) branch of the grammar repository. Here's a diff against the current version of the grammar: https://github.com/llir/grammar/commit/59372effc728f278949e7b46705dcdbba7c89b36

As you can see, we have tried to provide a generic grammar for parsing the specialized metadata nodes, even if this is not how the C++ parser was implemented. Perhaps it will work, perhaps not. The intention is to parse the AST into some high level representation of the DWARF debug data, but that step will happen after the grammar has been defined.

Some unfinished work can also be seen here, were we took the approach to add each specialized metadata node directly to the grammar, instead of having a generic representation: https://gist.github.com/mewmew/ae0633dc41f38b0fcaa9da79d52c6914

We most definitely welcome any input on this topic, as we feel quite stuck in deciding what seems to be the right approach to take.

Looking forward to hearing back from you.

Glada hälsningar,
Robin och Daniel :)

**Comment by mewmew** [comment]
As of rev 156ab38af4b57262c23963eace47a7bd5c05ddef, llir/llvm has support for specialized metadata nodes.

Closing this issue. If you notice any issues, just re-open this one, or open a new issue and report back.
