### ISSUE TITLE
Linking modules

### ISSUE THREAD

**Issue by nickwanninger** [llir/llvm#32]
First of all, I love this library. The LLVM bindings were a pain to work with because of their compile times and the fact it takes away the cross compilation that go gives us. But I am running in to a problem: In the current build, is there any way to define a function in one module, and use it in another one without erroring because it isn't defined?

Any help would be appreciated!

**Comment by mewmew** [comment]
Hi @nickwanninger!

Glad you like the library. Sure, it is possible to define a function in one module (say module 1) and use it in another module (say module 2). What you need to do is to declare it in module two, with the same name, return type and function paramter types.

You simply create the same function signature again, using `ir.NewFunction` or the method call `*ir.Module.NewFunction`. A function created this way is a function definition if it has any basic blocks added to it, and a function delcaration otherwise.

I've added an example below (https://play.golang.org/p/y-F97LvUNGk):
```go
package main

import (
	"io/ioutil"
	"log"

	"github.com/llir/llvm/ir"
	"github.com/llir/llvm/ir/constant"
	"github.com/llir/llvm/ir/types"
)

func main() {
	m1 := createModule1()
	m2 := createModule2()
	if err := ioutil.WriteFile("m1.ll", []byte(m1.String()), 0644); err != nil {
		log.Fatalf("%+v", err)
	}
	if err := ioutil.WriteFile("m2.ll", []byte(m2.String()), 0644); err != nil {
		log.Fatalf("%+v", err)
	}
}

// Note: f in createModule1 is a function definition as its body contains basic
// blocks (i.e. the entry basic block).
func createModule1() *ir.Module {
	// Create module 1 with function definition f.
	m1 := ir.NewModule()
	f := m1.NewFunction("f", types.I32)
	entry := f.NewBlock("entry")
	retVal := constant.NewInt(42, types.I32)
	entry.NewRet(retVal)
	return m1
}

// Note: f in createModule2 is a function declaration as its body contains no
// basic blocks.
func createModule2() *ir.Module {
	// Create module 2 with a call to function declaration f (defined in module
	// 1).
	m2 := ir.NewModule()
	f := m2.NewFunction("f", types.I32)
	main := m2.NewFunction("main", types.I32)
	entry := main.NewBlock("entry")
	callInst := entry.NewCall(f)
	entry.NewRet(callInst)
	return m2
}
```

Note, a key step is to use `llvm-link` to link the two modules if you later want to invoke them through the LLVM interpreter `lli`, as follows.

```bash
$ go run main.go 
$ ls
m1.ll  m2.ll  main.go
$ llvm-link -o out.ll m1.ll m2.ll
$ lli out.ll
$ lli out.ll; echo $?
42
```

Hope that may help.

Cheers,
/u

**Comment by mewmew** [comment]
@nickwanninger Did the above solution work out for you? I'll close this issue for now. Feel free to re-open if there is some other related issue to discuss :)
