### ISSUE TITLE
Add WriteTo(w) methods in addition to Def() to produce asm

### ISSUE THREAD

**Issue by pwaller** [llir/llvm#41]
At the moment, every Def() allocates its own string builder. This results in a lot of allocation and copying overhead for building IR outputs.

I don't (yet) have a benchmark showing this to be a problem, but in terms of API it would be nice to supply a writer and have the llvm package write directly there.

This issue is a reminder to come back to this.

**Comment by pwaller** [comment]
Quick update, I have played around with this. I can see it's a huge job, even with automation.

So I'm happy to put this in the category of "may not be worth it". I'll continue to play around privately, and if I can get any interesting performance results, I will be sure to report them here in this issue.

It seems unlikely at this point that I'll be able to reach my goal of testing against something like 'serialize sqlite and compare runtime and memory usage', though.

**Comment by mewmew** [comment]
The following comparison is based on rev 9c2e8ca9680265961af125c012a0ecde0042ce7d.

llir is 1.85x slower than LLVM to parse `shell.ll` of SQLite.

llir is 1.55x slower than LLVM to parse `vdir.ll` of Coreutils.

This puts us within 2x of LLVM, which should be good enough for the v0.3.0 release.

It would be great to improve this in the future! And there is definitely some low hanging fruit to be found. @pwaller has gotten a ~10% speed increase by making changes to Textmapper, so that the parser uses values instead of pointers for subtype (`%interface`) AST nodes, which puts less preasure on the Go garbage collector.

@pwaller, would you mind creating an issue to track the Textmapper work above so we don't loose it? Do you have the diff somewhere of what was needed? :)

The specifics for calculating the `llir` vs LLVM slowdown factor is presented below.

# SQLite

## LLVM

average real time: 1.69

```
$ time opt -verify < sqlite/test/shell.ll

real 1.69
user 1.58
sys 0.09

$ time opt -verify < sqlite/test/shell.ll

real 1.68
user 1.54
sys 0.12

$ time opt -verify < sqlite/test/shell.ll

real 1.70
user 1.57
sys 0.10
```

## llir

average real time: 3.12

```
$ time l-tm sqlite/test/shell.ll
asm: parsing into AST took: 1.318785166s
asm: index AST top-level entities took: 105.619707ms
asm: type resolution took: 1.635337ms
asm: create IR top-level entities took: 49.509083ms
asm: translate AST to IR took: 1.630427198s
asm: add IR definitions to IR module took: 50.121644ms
total time for file "sqlite/test/shell.ll": 3.193751643s

real 3.22
user 3.67
sys 0.25

$ time l-tm sqlite/test/shell.ll
asm: parsing into AST took: 1.332296208s
asm: index AST top-level entities took: 105.263225ms
asm: type resolution took: 1.654263ms
asm: create IR top-level entities took: 49.985311ms
asm: translate AST to IR took: 1.628654783s
asm: add IR definitions to IR module took: 49.276926ms
total time for file "sqlite/test/shell.ll": 3.205750564s

real 3.23
user 3.64
sys 0.29

$ time l-tm sqlite/test/shell.ll
asm: parsing into AST took: 1.333703175s
asm: index AST top-level entities took: 109.893044ms
asm: type resolution took: 1.653571ms
asm: create IR top-level entities took: 51.090025ms
asm: translate AST to IR took: 1.327419262s
asm: add IR definitions to IR module took: 49.214236ms
total time for file "sqlite/test/shell.ll": 2.899078532s

real 2.92
user 3.74
sys 0.28
```

# Coreutils

## LLVM

average real time: 0.22

```
$ time opt -verify < coreutils/test/vdir.ll

real 0.24
user 0.20
sys 0.03

$ time opt -verify < coreutils/test/vdir.ll

real 0.22
user 0.19
sys 0.02

$ time opt -verify < coreutils/test/vdir.ll

real 0.21
user 0.20
sys 0.01
```

## llir

average real time: 0.34

```
$ time l-tm coreutils/test/vdir.ll
asm: parsing into AST took: 183.7889ms
asm: index AST top-level entities took: 7.405762ms
asm: type resolution took: 135.637µs
asm: create IR top-level entities took: 4.598706ms
asm: translate AST to IR took: 147.208001ms
asm: add IR definitions to IR module took: 3.592691ms
total time for file "coreutils/test/vdir.ll": 355.543323ms

real 0.36
user 0.54
sys 0.03

$ time l-tm coreutils/test/vdir.ll
asm: parsing into AST took: 168.837893ms
asm: index AST top-level entities took: 9.344586ms
asm: type resolution took: 179.538µs
asm: create IR top-level entities took: 4.867541ms
asm: translate AST to IR took: 125.596136ms
asm: add IR definitions to IR module took: 3.579648ms
total time for file "coreutils/test/vdir.ll": 322.248448ms

real 0.32
user 0.40
sys 0.04

$ time l-tm coreutils/test/vdir.ll
asm: parsing into AST took: 166.491659ms
asm: index AST top-level entities took: 9.805071ms
asm: type resolution took: 244.146µs
asm: create IR top-level entities took: 11.506275ms
asm: translate AST to IR took: 130.762989ms
asm: add IR definitions to IR module took: 3.573189ms
total time for file "coreutils/test/vdir.ll": 332.843371ms

real 0.33
user 0.38
sys 0.05
```
