### ISSUE TITLE
How to add comments？

### ISSUE THREAD

**Issue by helperShang** [llir/llvm#99]
eg.
```
; Function Attrs: noinline norecurse nounwind optnone ssp uwtable
```

**Comment by mewmew** [comment]
Hi @helperShang, for an example of how to add comments as *pseudo-instructions*, see https://github.com/llir/llvm/issues/59#issue-394878876

There should probably be a more dedicated way to add comments, so that comments may appear anywhere and not just where instructions appear. Exactly how to do that is still being considered. Feel free to come with suggestions :)

Cheers,
Robin

**Comment by mewmew** [comment]
I'll re-open this issue as support for comments is fairly universal and should not have to be reimplemented by everyone. As such, the intention is to implement a canonical comment pseudo-instruction (roughly based on https://github.com/llir/llvm/issues/99#issuecomment-526333252) and add it to the [irutil](https://github.com/llir/irutil) package.
